version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn package
      - mv target/FirstWebProject.war FirstWebProject.war
artifacts:
  files:
    - FirstWebProject.war
    - .ebextensions/**/*
  base-directory: 'target/FirstWebProject'